version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: rest_api_db
    restart: always
    environment:
      TZ: 'America/Sao_Paulo'
      MYSQL_DATABASE: 'rest_api'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: '3308'
    ports:
      - '3308:3308'
    expose:
      - '3308'
    networks:
      - gabriel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  rest_api:
    image: rest_api
    container_name: rest_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - gabriel-network
networks:
  gabriel-network:
    driver: bridge
