name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven

      - name: Build Application JAR
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t gcristhie/rest_api:latest .

      - name: Tag Docker image with run ID
        run: docker tag gcristhie/rest_api:latest gcristhie/rest_api:${{ github.run_id }}

      - name: Push Docker image with run ID
        run: docker push gcristhie/rest_api:${{ github.run_id }}

      - name: Push Docker image as latest
        run: docker push gcristhie/rest_api:latest
